language: go

addons:
  ssh_known_hosts: beevee.ru

go:
- 1.7

before_install:
- go get github.com/mattn/goveralls
- go get github.com/kardianos/govendor
- govendor sync

script:
- goveralls
- pushd cmd/konfurbot && go build && ./konfurbot --checkmode && popd

before_deploy:
- openssl aes-256-cbc -K $encrypted_f10f3c59f737_key -iv $encrypted_f10f3c59f737_iv
  -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script:
  - rsync --quiet $TRAVIS_BUILD_DIR/cmd/konfurbot/konfurbot deploy@beevee.ru:/opt/konfurbot/
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script:
  - rsync --quiet $TRAVIS_BUILD_DIR/cmd/konfurbot/schedule.yml deploy@beevee.ru:/opt/konfurbot/
  on:
    branch: master
- provider: script
  script:
  - ssh deploy@beevee.ru 'sudo systemctl restart konfurbot'
  on:
    branch: master

env:
  global:
    secure: KueKCzAQVHQ13GU0o2ZZXQtILiVtJ9lnB0mKo9loFT0gl2y6AVsxRcuvouhjNpTAUwCC3GbOrT9UcdyOYcBZYIvcntCQKdHp1ehymdIJWYZaVAXk2uK1HYEJXIKKrIvJbKzys8alp+MFhnWcRJ5r8AScOnVHvdmcsZC1Gka1tqBsFYdlyafj0Hc62FdC+YYfllnLnA/nFJBBaiBMIZGrUrbmnvkmwrca02nyze8mcPHFqYVtOUoxMJX+ZqyH6CHJdytA+JqWwJRyslTLfk/r17NdDmKpQpYkB2mw+dVHQc3UJb/XGehjbNzOW/rkDhsSToESx8LmpqLXITLxpxK+1TKIO8w6NTEyslh+NnT0lyvFD6f41EX0A99vXQ2lk8bOpEUGh6dbjPBFLAzIc5ZxX0d2X3jUwfk2Rn29pPdGWgBgRc4bPQ23rZDO8MXWoXMB4E66PgfIHGpwz9/KLk40TVBP+aESK32ogkqlxrG4lW6Wg44wPxbO3Z4rs9qAqtu76YaKN86K8nlJGsWOkcPMzGh2ZnFkelcRGW6pwns/GUJZBsssMcuCC2+co7UsGv+f5A94j8g927osCsZd2VZ1JoAXl7SXwuypPvv/jb9iq4XiSXhnguL55t9qKHjxz9NzQLP0+CnpDugZ+Nyxea5nS+f/TZhxH/PkRiTABKsJ0EU=
